apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15.0
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "user"
            - name: POSTGRES_PASSWORD
              value: "password123"
            - name: POSTGRES_DB
              value: "temperature_db"

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: temperature-converter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: temperature-converter
  template:
    metadata:
      labels:
        app: temperature-converter
    spec:
      containers:
        - name: temperature-converter
          image: nilsonsangy/temperature-converter:v2.0
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          env:
            - name: DB_DATABASE
              value: "temperature_db"
            - name: DB_USERNAME
              value: "user"
            - name: DB_PASSWORD
              value: "password123"
            - name: DB_HOST
              value: postgres

---

apiVersion: v1
kind: Service
metadata:
  name: temperature-converter
spec:
  selector:
    app: temperature-converter
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      # nodePort: 30000